repos:
# Add this below the pre-commits we set up before
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.10 # Change this if a new version is out.
  hooks:
    # Apply Ruff linting fixes.
    - id: ruff
      name: ruff fix # We can add arbitrary names to our hooks
      args: [ --fix ]
      types_or: [ python, pyi ] # Only scan .py files (and not jupyter notebooks)

    # Run the formatter.
    - id: ruff-format
      name: ruff format
      types_or: [ python, pyi ] # Only format .py files (and not jupyter notebooks)

    # Run the linter one last time to check for remaining issues.
    - id: ruff
      name: ruff check
      args: [ --output-format concise ] # Makes the ruff check output more legible.
      types_or: [ python, pyi ] # Only scan .py files (and not jupyter notebooks)